### ISSUE TITLE
Minimal example

### ISSUE THREAD

**Issue by spethso** [UST-MICO/mico#217]
- [x] Search for an appropriate GitHub repository containing a Dockerfile.
- [x] Add URL of the GitHub repository in the UI to import the given application in MICO as service
- [x] Create the (deployable) application from the imported service in MICO
- [x] Deploy the application
- [x] Show runtime informations in the UI

**Comment by davidkopp** [comment]
Simple GitHub repository containing a Dockerfile: https://github.com/dgageot/hello.git
