### ISSUE TITLE
Improve code quality

### ISSUE THREAD

**Issue by JakobBenz** [UST-MICO/mico#527]
This is the bucket list for refactorings regarding improving the code quality of team Tuesday. See also bucket list of team Monday: #481.

- [x] Refactor `ServiceInterfaceController`, see #491.
- [x] Refactor `ServiceController`, see #490.
- [x] Refactor `PrometheusResponse`, see #427.
- [x] Remove `ClusterAwareness`, see #450.
- [x] Refactor `TestConstants`, see #536.
- [x] Consistent use of `ArrayList` instead of `LinkedList`.
- [x] Replace `ResponseEntity<?>` with specific response type, covered by #543.
- [x] Improve error log statements (don't use `getStackTrace()`).
- [x] Remove unnecessary annotations form `buildtypes` in `imagebuilder` (e.g. `JsonInclude` and `Builder`).
- [ ] Consistent logging (when and what, naming convetions (`MicoService` vs. `service`), ...).
- [x] Consistent use of `Task` or `Job` in all classes that refer to the state handling for running jobs, see #580.
- [x] Remove yaml files in `test/resources`.
- [x] Rename endpoint `deleteAllVersionsOf**An**Application` to `deleteAllVersionsOfApplication`.
- [x] Rename endpoint `getServicesFromApplication` to `getServicesOfApplication`.
- [ ] Consistent grouping / order of endpoints.
- [x] Remove `MicoCoreApplicationTests`.
- [x] Remove `LombokFluentChainTests`.
