### ISSUE TITLE
M3 Scenario (Roadmap)

### ISSUE THREAD

**Issue by miwurster** [UST-MICO/mico#712]
- [ ] Gather knowledge to decide implementation strategy for composition patterns
- [ ] Validate FaaS frameworks for usage in M3
- [ ] Implement a generic framework for custom logic patterns (e.g., transformer, splitter, et al.)
  - Generic component is able to work with Kafka layer
  - Custom logic is provided as a function (any lang)
  - Evaluate how to map function with an instance of a generic component
- [ ] Decide which patterns are implemented specifically
- [ ] Evaluate MICO domain model in order to represent composition patterns (see separate example)
