### ISSUE TITLE
As a user, I want to use the kafka-faas-connector multiple times in the same MicoApplication.

### ISSUE THREAD

**Issue by miwurster** [UST-MICO/mico#750]
Depends on #743

Goals:
- We want to deploy the *KafkaFaasConnector* multiple times in the same application
- The *KafkaFaasConnector* should be scaled independently

---

**Discussed solution:**

- [x] Update domain model: #790
  
  *New property in `MicoApplication`:*
  ```
  private List<MicoServiceDeploymentInfo> kafkaFaasConnectorDeploymentInfos = new ArrayList<>();
  ```

*New endpoints:*
- [x] `ApplicationResource`:
   - [x] `addKafkaFaasConnectorInstanceToApplication`:  #790
     - Add new service deployment information to the list `kafkaFaasConnectorDeploymentInfos`
     - Generate unique `instanceId` and return it
     - [x] Change current implementation to
`/<short-name>/<version>/kafka-faas-connector/<kf-connector-version>/<instance-id>`: #796
   - [x] `deleteKafkaFaasConnectorInstanceFromApplication`:  #790
     -  Additional parameter: `instanceId`
     - [x] Change current implementation to
`/<short-name>/<version>/kafka-faas-connector/<kf-connector-version>/<instance-id>`: #793
    - [x] Remove `kf-connector-version` as path variable #811 

- [x] `KafkaFaasConnectorDeploymentInfoResource`: #798
   - [x] Get all #809
   - [x] Get specific deployment info
   - [x] Update #812

*Change implementation of endpoints (or at least check if changes are necessary):*
- [x] `getApplicationDeploymentStatus`:
   Deployment status of the application should consider the current status of the deployed the KafkaFaasConnector(s)
- [x] `getStatusOfApplication`: #802
   Status of application should include the information of the KafkaFaasConnector(s).
- [x] `deploy` / `undeploy`:
   - [x] KafkaFaasConnectors must be deployed / undeployed alongside normal MicoServices #801
   - [x] Add appropriate checks for kafka-enabled services: #820
- [x] `addMicoServiceToMicoApplicationByShortNameAndVersion`
  Add a check if the new MicoService is a KafkaFaasConnector
*Misc:
- [x] Add `KubernetesDeploymentInfo` to `KFConnectorDeploymentInfoResponseDTO` #800 
- [x] Ensure that default deployment information is applied when a new KafkaFaasConnector deployment information is added to an application #831

*Notes:*
- `KafkaFaasConnectorDeploymentInfo` should be addressed either by an `instanceId` per application or with a global unique ID. `instanceId` is unique per KafaFaasConnector within an application regardless of its version.
- For the edge between the `MicoApplication` node and the `KafkaFaasConnectorDeploymentInfo` nodes use a different name than `PROVIDES` -> e.g. `PROVIDES_KF_CONNECTOR`
- If we need an edge between the `MicoApplication` node and the KafkaFaasConnector node don't call `INCLUDES`.

*Updated domain model:*
![image](https://user-images.githubusercontent.com/7796322/63770491-9252cd00-c8d5-11e9-8d0a-ff59d505f4ad.png)

**Comment by davidkopp** [comment]
New property in *MicoApplication*:
```
private List<KafkaFaasConnectorDeploymentInfo> = new ArrayList<>();
```

New endpoints:
- `ApplicationResource`:
   - `addKafkaFaasConnectorToApplication`
   - `deleteKafkaFaasConnectorToApplication`
   - `getKafkaFaasConnectorDeploymentInformation`
   - `updateKafkaFaasConnectorDeploymentInformation`
- `KafkaFaasConnectorDeploymentInfoResource`:
   - `getKafkaFaasConnector`
   - `updateKafkaFaasConnector`
   - `promoteKafkaFaasConnector`
   - `deleteKafkaFaasConnector`

Change implementation of endpoints:
- `getApplicationDeploymentStatus`
- `getStatusOfApplication`

Notes:
- `KafkaFaasConnectorDeploymentInfo` should be addressed either by an `instanceId` per application or with a global unique ID. `instanceId` is unique per KafaFaasConnector within an application regardless of its version.
- For the edge between the `MicoApplication` node and the `KafkaFaasConnectorDeploymentInfo` nodes use a different name than `PROVIDES` -> e.g. `PROVIDES_KF_CONNECTOR`
- If we need an edge between the `MicoApplication` node and the KafkaFaasConnector node don't call `INCLUDES`.

**Comment by davidkopp** [comment]
![image](https://user-images.githubusercontent.com/7796322/63355253-249f2200-c366-11e9-932f-73746160219d.png)

**Comment by wagnerdk** [comment]
Remove version from all paths related to KafkaFaasConnectorDeploymentInformation.
